spring.application.name=cms-backend
server.port=8080

# Supabase PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://aws-0-ap-southeast-1.pooler.supabase.com:5432/postgres?sslmode=require
spring.datasource.username=postgres.ujcwensseevsbkdhnotv
spring.datasource.password=Adnan@123az
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT Configuration
app.jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
app.jwt.expiration-ms=86400000

# Cloudinary Credentials Configuration
cloudinary.cloud-name=tambvqrv
cloudinary.api-key=297869423192439
cloudinary.api-secret=YWQl-Sb1oAdwQkI2L2LFlZFhoMk

# Mail Configuration (For Contact Form notifications)
spring.mail.host=${MAIL_HOST:smtp.gmail.com}
spring.mail.port=${MAIL_PORT:587}
spring.mail.username=${MAIL_USERNAME:your-email@gmail.com}
spring.mail.password=${MAIL_PASSWORD:your-app-password}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# File Upload Max Size
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
